services:
  postgres:
    image: postgres:15-alpine
    container_name: notify-engine-db
    environment:
      POSTGRES_DB: notifyengine
      POSTGRES_USER: notifyengine
      POSTGRES_PASSWORD: notifyengine
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
